apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
              envs:
                - name: ME_CONFIG_MONGODB_ADMINUSERNAME
                  valueFrom:
                    secretKeyRef:
                    name: mongo-secret
                    key: mongo-root-username
                - name: ME_CONFIG_MONGODB_ADMINPASSWORD
                  valueFrom:
                    secretKeyRef:
                    name: mongo-secret
                    key: mongo-root-password
                - name: ME_CONFIG_MONGODB_SERVER
                  valueFrom:
                    configMapKeyRef:
                    name: mongodb-configmap
                    key: database_url
